C     TITCOM.INC
C     Titles COMMON block
C     jw 14-04-85
C     jw 28-11-04 last rev	

      COMMON /TITCOM/ TITLE1, TITLE2, TITLE3,
     +                DESC,   AUTH,   CPRT,   ENG,
     +                DATE,   PROG,   PDAT,   VERS,
     +                PADOUT,
     +                IPAGE, MLINE, ILINE,
     +                LP,LV,LD,LA,LE,
     +                COLW1,COLW2,COLW3,COLFRE,
     +                LT1,LT2,LT3,MORXX,KOL3

C    titcom.inc
